### PR TITLE
Remove the requirement for user email verification

### PR DESCRIPTION
**Pull request by thomik-corp**
Fixes: https://github.com/mozilla-rally/rally/issues/276

### CODE REVIEW

**Review by rhelmer — APPROVED** [review]
This looks great! The code changes lgtm overall, but when I test locally I found a few issues but I think they might both be pre-existing:

- (minor) there's a flash of the studies page before the consent agreement is shown
- https://github.com/mozilla-rally/rally/issues/302 - at first I thought this was a bug related to an unverified account, but I think this feature isn't working on production either.

I would like to understand how the "reset password" feature is meant to work on an unverified account, should it send a password, or should it refuse until the account is verified? I think that we need to be careful how many and what sorts of email we send to unverified accounts.

**Comment by rhelmer** [comment]
> I would like to understand how the "reset password" feature is meant to work on an unverified account, should it send a password, or should it refuse until the account is verified? I think that we need to be careful how many and what sorts of email we send to unverified accounts.

To be clear, I think this is probably more up to Firebase than us, but I'd like to understand the behavior and what we might do about it (we might need to continue show an unverified error in response to "forget password" dialogs for instance)

**Comment by rhelmer** [comment]
I've seen this a few times while testing locally, but doesn't seem consistently reproducible. I'll see if I can track down what permission it is, seems to be right after creating a new account, before accepting the privacy policy:

image

**Comment by Carla-Moz** [comment]
> > I would like to understand how the "reset password" feature is meant to work on an unverified account, should it send a password, or should it refuse until the account is verified? I think that we need to be careful how many and what sorts of email we send to unverified accounts.
> 
> To be clear, I think this is probably more up to Firebase than us, but I'd like to understand the behavior and what we might do about it (we might need to continue show an unverified error in response to "forget password" dialogs for instance)

Yes, I agree we should show the unverified email copy on the card before allowing users to update their password. I'll file an issue for this. This also affects accounts forget password, update email, and update password flows. Users should see an unverified email feedback before attempting any of these actions. Will file issues for this as well.

**Review by Carla-Moz — APPROVED** [review]
This works for me locally. I'll create issues to address Rob's concerns about "update password" feedback for unverified email, along with on accounts. I can take care of it.

**Pull request merged**
