### PR TITLE
New onboarding flow with new two column layout and text

### PR DESCRIPTION
**Pull request by thomik-corp**
To test this feature you must set a flag in local storage. In your browser, define the following key in the local storage by running this command in the console:
```
localStorage.setItem("flags", JSON.stringify({onboardingV2: true}));
```

Then refresh the page and you should see new experience as signed out user!

Note: We still need to add logic to the page to detect extensions and display text appropriately.

Initial screen
image

Sign up with email
image

Login
image

Forgot password
image

### CODE REVIEW

**Comment by Carla-Moz** [comment]
On chrome only, trailing eye icon. 

Screen Shot 2022-10-05 at 2 12 37 PM

**Comment by Carla-Moz** [comment]
The link to reset password doesn't work. It loads perpetually... could you please test again?

**Comment by Carla-Moz** [comment]
Also when entering the wrong password and receiving error feedback, typing in the field doesn't return input to the default state... So, I can't hide my password now.

Screen Shot 2022-10-05 at 2 32 05 PM

**Review by Carla-Moz — COMMENTED** [review]
Added some comments to your PR above

**Comment by thomik-corp** [comment]
I am able to reset password correctly 
image

**Comment by thomik-corp** [comment]
Fixed the email signup password show/hide.

image

**Comment by Carla-Moz** [comment]
> I am able to reset password correctly image
> 
> image

Must have been an anomaly on my end then!

**Review by Carla-Moz — APPROVED** [review]

**Comment by thomik-corp** [comment]
I also fixed the invalid password error where we now clear it if user changes it from last error.

**Pull request merged**
